### ISSUE TITLE
FAILED_PRECONDITION Should Map to HTTP 412

### ISSUE THREAD

**Issue by bkoerner** [googleapis/googleapis.github.io#9]
The mapping file in google/rpc/code.proto states the HTTP code for FAILED_PRECONDITION is "400 Bad Request".  It seems like this would more naturally map to [412 "Precondition Failed"](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml), as specified in RFC 7232.  Using 400 makes the mapping unidirectional; there are other Google API status codes that also map to 400, so we have to map any 400 coming back as INVALID_ARGUMENT rather than allowing a more precise mapping.

I'll also note, [google.api_core.exceptions](https://google-cloud-python.readthedocs.io/en/0.32.0/_modules/google/api_core/exceptions.html) maps PreconditionFailed to 412.  It seems like the status codes here should map the same way.

**Comment by lukesneeringer** [comment]
I was curious about this so I looked into it.

Looking at the HTTP spec, the current behavior seems "technically correct (the best kind of correct)"...

> The HTTP 412 Precondition Failed client error response code indicates that access to the target resource has been denied. This happens with conditional requests on methods other than GET or HEAD when the condition defined by the `If-Unmodified-Since` or `If-None-Match` headers is not fulfilled. In that case, the request, usually an upload or a modification of a resource, cannot be made and this error response is sent back.

In other words, since gRPC never uses the two specific headers earmarked for that response code, the response code is inappropriate.

I leave it as an exercise for the reader to decide how compelling that answer is. Personally, I can make a pretty decent argument in my own head that mapping to 412 would have been a better result for users, regardless of what the spec says. (Actual use of _many_ HTTP codes has evolved from what the spec originally expected.)

That said, at this point we have five years behind us with a _lot_ of prior art, and we would probably break a lot of people if we changed it.
